version: '3.8'

services:
  frontend:
    container_name: vue-frontend
    image: bydaniel1111/docker-front-deployement:07
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
      - "5556:443"  
    restart: always
