version: '3.8'

services:
  frontend:
    container_name: vue-frontend
    image: bydaniel1111/docker-front-deployement:02
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
    volumes:
      # Montar assets para desarrollo si es necesario
      - ./src/assets:/usr/share/nginx/html/src/assets
    restart: always